### ISSUE TITLE
Error on callback

### ISSUE THREAD

**Issue by aleksholt** [Moiv/eve-sso#2]
Hi. After config I try to auth, but have this problem on redirect to callback.php.

`Fatal error: Uncaught ArgumentCountError: Too few arguments to function eve\sso\KeyChain::__construct(), 1 passed in /var/www/u0611307/data/www/eve.recoverysolutions.ru/callback.php on line 14 and exactly 3 expected in /var/www/u0611307/data/www/eve.recoverysolutions.ru/KeyChain.php:30 Stack trace: #0 /var/www/u0611307/data/www/eve.recoverysolutions.ru/callback.php(14): eve\sso\KeyChain->__construct(Object(eve\sso\FSTokenStorer)) #1 {main} thrown in /var/www/u0611307/data/www/eve.recoverysolutions.ru/KeyChain.php on line 30`

**Comment by Moiv** [comment]
Hi Aleks,
So sorry for the slow response, I did not get a notification from github that an issue had been reported.
Did you manage to get around the problem?

The problem was that constants had been removed from the KeyChain class and moved into the calling API code, however when this change was made it was not also made in the callback.php file as well.

I have never experienced the bug in callback.php because once you have received the auth tokens the callback.php file shouldn't need to be called again.

I have pushed a fix to callback.php

Thank you for reporting it the problem!
